### ISSUE TITLE
Folder/Files does not exist

### ISSUE THREAD

**Issue by vdellaglio** [groovemonkey/hands_on_linux-self_hosted_wordpress_for_linux_beginners#1]
Hi Dave,

After running this command: apt-get install php-json php-xmlrpc php-curl php-gd php-xml php-mbstring

The expected folder "/etc/php5..." does not exist. Looking at the /var/run I can only see (php related): php and php-fpm

I am at section 4, Lecture 29, at 06;10 of the video.

Thanks

**Comment by vdellaglio** [comment]
UPDATE:

Comparing the command you ran and the command you provided here, I can see that yours have several "php5..", while here it is only php, example: php-json (github), php5-json (video)

**Comment by groovemonkey** [comment]
Hi there! Which version of Ubuntu are you using? The github documentation is the one I keep up-to-date, so that should always take precedence over the specific commands you see in the video. Since the course was filmed, PHP has had a major version update with a bunch of config file locations changing.

**Comment by vdellaglio** [comment]
Hey,

Thanks for the prompt reply. I am using Ubuntu 16.04

I believe I found the issue:

When I go to this github project I get to this page:
https://github.com/groovemonkey/hands_on_linux-self_hosted_wordpress_for_linux_beginners

Then I just click on the "5-basic-phpfpm-and-php-configuration.md" and it gets me to:
https://github.com/groovemonkey/hands_on_linux-self_hosted_wordpress_for_linux_beginners/blob/master/5-basic-phpfpm-and-php-configuration.md

Seems that this is not the most up to date version. Sorry if I am doing something wrong, I am new-user on github. Looking at the Q&A on the course I could find this updated page here, with instructions for ubuntu 16.04:
https://github.com/groovemonkey/hands_on_linux-self_hosted_wordpress_for_linux_beginners/blob/655e44bee950e43f90c04997058ccac8264f68f4/5-basic-phpfpm-and-php-configuration.md

Not sure why this is not the default page for step 5. Is it wrong or I am doing something wrong?

Thanks again for your time.

**Comment by groovemonkey** [comment]
Ah, thanks for clarifying. Yes, the first page you linked is actually the newest one -- I removed instructions for Ubuntu 15.10 and earlier, since they are no longer supported (and in the case of 14.04, no longer really used for new projects).

Just to make sure I understand: are you experiencing an error when following along to the videos with the (updated) instructions on Github?

Or is it just the confusion of seeing config directories and service names that are slightly different vs what you see in the video (I agree that it's annoying, sorry about that!)?

Happy to keep helping, either way!

**Comment by vdellaglio** [comment]
Ok, let's go:

You are telling me that this page is the updated one, correct?
https://github.com/groovemonkey/hands_on_linux-self_hosted_wordpress_for_linux_beginners/blob/master/5-basic-phpfpm-and-php-configuration.md

So following this page I get stuck when I restart the service. Looking at the log I found:

> [01-Apr-2018 11:35:08] ERROR: failed to post process the configuration
> [01-Apr-2018 11:35:08] ERROR: FPM initialization failed
> **[01-Apr-2018 11:35:08] ERROR: No pool defined. at least one pool section must be specified in config file**

Looking at the directory "/etc/php/7.0/fpm/pool.d/" it is empty now.

When looking at the github page you tell us to delete the original pool:
> Remove the original (default) pool:
> rm /etc/php/7.0/fpm/pool.d/www.conf

but then there are no instructions to create a new one.

The other page I mentioned...

https://github.com/groovemonkey/hands_on_linux-self_hosted_wordpress_for_linux_beginners/blob/655e44bee950e43f90c04997058ccac8264f68f4/5-basic-phpfpm-and-php-configuration.md

...has the correct instructions, following it works! You instruct us there to create a new pool and you also provide the contents. 

What I think it happened is:  you edited the page (removed instructions for Ubuntu 15.10 and earlier) and when you updated the link on github you pointed to a incomplete version.

I hope it is clear now, and I also hope I am not crazy :-)

**Comment by groovemonkey** [comment]
Yikes, you're absolutely right! Sorry about that! I'll fix the new version ASAP; thanks for letting me know.

**Comment by groovemonkey** [comment]
Just fixed it -- thanks! https://github.com/groovemonkey/hands_on_linux-self_hosted_wordpress_for_linux_beginners/blob/master/5-basic-phpfpm-and-php-configuration.md

**Comment by vdellaglio** [comment]
You are more than welcome!

Cheers!

Best regards,
---
Vinícius Dell'Aglio
+353 83 8445799
*http://linkedin.com/in/viniciusdellaglio
<http://linkedin.com/in/viniciusdellaglio>*
MCSA - Microsoft Certified Solutions Associate - Windows Server 2012
MS: Server Virtualization with Windows Server Hyper-V and System Center
Specialist
MCSE - Microsoft Certified Systems Engineer - Windows Server 2003
MCSA - Microsoft Certified Systems Administrator - Windows Server 2003
MCTS - Microsoft Certified Technology Specialist - Exchange Server 2007,
Configuration
MCDST - Microsoft Certified Desktop Technician - Windows XP
MCP - Microsoft Certified Professional
