### ISSUE TITLE
how to configrution stmp with nginx 

### ISSUE THREAD

**Issue by Khalidalansi** [groovemonkey/hands_on_linux-self_hosted_wordpress_for_linux_beginners#3]
when test send email i get message 
 The IP you're using to send mail is not authorized to 550-5.7.1 send email directly to our servers. Please use the SMTP relay at your 550-5.7.1 service provider instead. Learn more at 550 5.7.1  https://support.google.com/mail/?p=NotAuthorizedError z12si37531265qkf.212 - gsmtp (in reply to end of DATA co

or 
 550 Access denied - Invalid HELO name

**Comment by groovemonkey** [comment]
Woops, sorry I never saw this issue! Looks like a provider IP issue for sending mail -- workaround is in the message. Seeing as how that was in 2019, I'm sure you figured it out 🤣
