### ISSUE TITLE
mysql server loading errors

### ISSUE THREAD

**Issue by W1RPQ** [groovemonkey/hands_on_linux-self_hosted_wordpress_for_linux_beginners#7]
Cant seem to get mysql to load without errors. I have removed it and still have issues loading.
!
![mysql error](https://github.com/groovemonkey/hands_on_linux-self_hosted_wordpress_for_linux_beginners/assets/61468143/522ddf0f-a7a5-40d6-8b0c-d0038c305c30)

**Comment by groovemonkey** [comment]
I can take a look and see if I can reproduce. Couple of questions:

1. Is this on Ubuntu 22.04?
2. Is this on a local VM or DigitalOcean/AWS/another host?

Once I hear back I'll try to reproduce and let you know what I find.

**Comment by groovemonkey** [comment]
Closing for now -- feel free to reopen with more details if you're still having this issue!
